<?php

namespace App\Http\Controllers;

use App\Models\Account;
use App\Models\AccountTransaction;
use App\Models\CashTransaction;
use App\Models\Purchase;
use App\Models\Sale;
use App\Services\PurchaseService;
use App\Services\SaleService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use RuntimeException;

class AccountTransactionController extends Controller
{
    public function store(Request $request, Account $account)
    {
        $data = $request->validate([
            'type' => ['required', Rule::in(['manual_debt', 'manual_credit'])],
            'amount' => ['required', 'numeric', 'min:0.01'],
            'description' => ['nullable', 'string', 'max:255'],
            'transaction_date' => ['nullable', 'date'],
        ]);

        $account->transactions()->create([
            'type' => $data['type'],
            'direction' => AccountTransaction::TYPE_DIRECTIONS[$data['type']],
            'amount' => $data['amount'],
            'description' => $data['description'] ?? null,
            'transaction_date' => $data['transaction_date'] ?? now(),
            'user_id' => $request->user()->id,
        ]);

        return back()->with('success', 'Cari hareket eklendi.');
    }

    /**
     * Cancelling a collection/payment must also reverse the cash_transactions
     * row it is linked to (via the source morph), atomically, so the two
     * ledgers never drift apart.
     *
     * A row generated by a Sale/Purchase (WP-4) carries source = that
     * document instead, since a sale/purchase can have up to three linked
     * rows (debt + payment + cash) that must all be reversed together — so
     * cancelling any one of them here delegates to Sale/PurchaseService,
     * which reverses the whole chain atomically.
     */
    public function cancel(Request $request, AccountTransaction $accountTransaction)
    {
        try {
            if ($accountTransaction->source_type === Sale::class) {
                app(SaleService::class)->cancel(Sale::findOrFail($accountTransaction->source_id), $request->user());

                return back()->with('success', 'Satış iptal edildi.');
            }

            if ($accountTransaction->source_type === Purchase::class) {
                app(PurchaseService::class)->cancel(Purchase::findOrFail($accountTransaction->source_id), $request->user());

                return back()->with('success', 'Alış iptal edildi.');
            }

            DB::transaction(function () use ($request, $accountTransaction) {
                $accountTransaction->cancel($request->user());

                if ($accountTransaction->source_type === CashTransaction::class) {
                    $linkedCash = CashTransaction::find($accountTransaction->source_id);

                    if ($linkedCash && ! $linkedCash->isCancelled()) {
                        $linkedCash->cancel($request->user(), 'İlişkili cari hareket iptal edildi: '.$accountTransaction->typeLabel());
                    }
                }

                $this->reverseAppliedPayment($accountTransaction);
            });
        } catch (RuntimeException $e) {
            return back()->with('error', $e->getMessage());
        }

        return back()->with('success', 'Hareket iptal edildi.');
    }

    /**
     * If this manual collection/payment (WP-10e) had been applied against a
     * specific open Sale/Purchase, cancelling it must give that amount back
     * to the document's remaining balance — otherwise paid_amount would stay
     * inflated after the money that funded it was reversed.
     */
    private function reverseAppliedPayment(AccountTransaction $accountTransaction): void
    {
        if (! $accountTransaction->applies_to_type || ! $accountTransaction->applies_to_id) {
            return;
        }

        $document = $accountTransaction->applies_to_type::find($accountTransaction->applies_to_id);

        if (! $document) {
            return;
        }

        $document->decrement('paid_amount', $accountTransaction->amount);
        $document->refresh();

        $paidAmount = (float) $document->paid_amount;

        $document->update([
            'status' => match (true) {
                $paidAmount <= 0 => 'unpaid',
                $document->remaining() <= 0 => 'paid',
                default => 'partial',
            },
        ]);
    }
}
