<?php

namespace App\Http\Controllers;

use App\Models\Account;
use App\Models\AccountTransaction;
use App\Models\CashTransaction;
use App\Models\Purchase;
use App\Models\Sale;
use App\Services\PurchaseService;
use App\Services\SaleService;
use App\Support\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use RuntimeException;

class CashTransactionController extends Controller
{
    private const MANUAL_TYPES = ['other_income', 'expense', 'manual_in', 'manual_out'];

    public function index(Request $request)
    {
        $transactions = CashTransaction::with(['account', 'user'])
            ->when($request->type, fn ($q) => $q->where('type', $request->type))
            ->when($request->date_from, fn ($q) => $q->whereDate('transaction_date', '>=', $request->date_from))
            ->when($request->date_to, fn ($q) => $q->whereDate('transaction_date', '<=', $request->date_to))
            ->orderByDesc('transaction_date')
            ->orderByDesc('id')
            ->paginate(25)
            ->withQueryString();

        // Balance and today's in/out per currency — TL/USD/EUR summary cards
        // never blend into one figure; a currency only gets its own card
        // when it actually has activity (balancesByOne() aside, TL/its own
        // balance() alias stay backward compatible for any other caller).
        $balancesByCurrency = CashTransaction::balancesByCurrency();
        $todayInByCurrency = CashTransaction::where('direction', 'in')->whereDate('transaction_date', today())
            ->selectRaw('currency, SUM(amount) as total')->groupBy('currency')->pluck('total', 'currency');
        $todayOutByCurrency = CashTransaction::where('direction', 'out')->whereDate('transaction_date', today())
            ->selectRaw('currency, SUM(amount) as total')->groupBy('currency')->pluck('total', 'currency');

        $cashSummaries = collect(Currency::LIST)
            ->filter(fn ($currency) => $currency === 'TL'
                || $balancesByCurrency->has($currency)
                || $todayInByCurrency->has($currency)
                || $todayOutByCurrency->has($currency))
            ->map(fn ($currency) => [
                'currency' => $currency,
                'balance' => (float) ($balancesByCurrency[$currency] ?? 0),
                'today_in' => (float) ($todayInByCurrency[$currency] ?? 0),
                'today_out' => (float) ($todayOutByCurrency[$currency] ?? 0),
            ])
            ->values();

        $accounts = Account::where('active', true)->orderBy('name')->get();

        return view('cash.index', compact('transactions', 'cashSummaries', 'accounts'));
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'type' => ['required', Rule::in(self::MANUAL_TYPES)],
            'amount' => ['required', 'numeric', 'min:0.01'],
            'currency' => ['nullable', Rule::in(Currency::LIST)],
            'description' => ['nullable', 'string', 'max:255'],
            'account_id' => ['nullable', 'exists:accounts,id'],
            'transaction_date' => ['nullable', 'date'],
        ]);

        CashTransaction::create([
            'type' => $data['type'],
            'direction' => CashTransaction::TYPE_DIRECTIONS[$data['type']],
            'amount' => $data['amount'],
            'currency' => $data['currency'] ?? 'TL',
            'description' => $data['description'] ?? null,
            'account_id' => $data['account_id'] ?? null,
            'transaction_date' => $data['transaction_date'] ?? now(),
            'user_id' => $request->user()->id,
        ]);

        return back()->with('success', 'Kasa hareketi eklendi.');
    }

    /**
     * Cancelling a collection/payment cash row must also reverse the linked
     * account_transaction, atomically, so the two ledgers never drift apart.
     *
     * A row generated by a Sale/Purchase (WP-4) carries source = that
     * document instead — cancelling it here delegates to Sale/PurchaseService
     * so the whole chain (stock + debt + payment + cash) reverses together.
     */
    public function cancel(Request $request, CashTransaction $cashTransaction)
    {
        try {
            if ($cashTransaction->source_type === Sale::class) {
                app(SaleService::class)->cancel(Sale::findOrFail($cashTransaction->source_id), $request->user());

                return back()->with('success', 'Satış iptal edildi.');
            }

            if ($cashTransaction->source_type === Purchase::class) {
                app(PurchaseService::class)->cancel(Purchase::findOrFail($cashTransaction->source_id), $request->user());

                return back()->with('success', 'Alış iptal edildi.');
            }

            DB::transaction(function () use ($request, $cashTransaction) {
                $cashTransaction->cancel($request->user());

                if ($cashTransaction->source_type === AccountTransaction::class) {
                    $linkedAccount = AccountTransaction::find($cashTransaction->source_id);

                    if ($linkedAccount && ! $linkedAccount->isCancelled()) {
                        $linkedAccount->cancel($request->user(), 'İlişkili kasa hareketi iptal edildi: '.$cashTransaction->typeLabel());
                        $this->reverseAppliedPayment($linkedAccount);
                    }
                }
            });
        } catch (RuntimeException $e) {
            return back()->with('error', $e->getMessage());
        }

        return back()->with('success', 'Hareket iptal edildi.');
    }

    /**
     * If the account_transaction paired with this cash row had been applied
     * (WP-10e) against a specific open Sale/Purchase, cancelling it here
     * must give that amount back to the document's remaining balance —
     * otherwise paid_amount would stay inflated after the money that funded
     * it was reversed.
     */
    private function reverseAppliedPayment(AccountTransaction $accountTransaction): void
    {
        if (! $accountTransaction->applies_to_type || ! $accountTransaction->applies_to_id) {
            return;
        }

        $document = $accountTransaction->applies_to_type::find($accountTransaction->applies_to_id);

        if (! $document) {
            return;
        }

        $document->decrement('paid_amount', $accountTransaction->amount);
        $document->refresh();

        $paidAmount = (float) $document->paid_amount;

        $document->update([
            'status' => match (true) {
                $paidAmount <= 0 => 'unpaid',
                $document->remaining() <= 0 => 'paid',
                default => 'partial',
            },
        ]);
    }
}
